omap-usb-install: add command line options [make | run [32|64]]

diff --git a/omap-usb-install b/omap-usb-install
--- a/omap-usb-install
+++ b/omap-usb-install
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# From https://github.com/networkimprov/omap3-usb-boot-install
 #
 # Install script to cold flash over USB using an image made of
 # subimages for MLO, u-boot, script, dtb, zimage and initrd.
@@ -24,52 +25,69 @@ SZ_2M=2097152
 SZ_8M=8388608
 SZ_20M=20971520
 
-generate_install_script() {
-	if ! mkimage -A arm -T script -C none -n "Install script" -d boot.script boot.scr; then
-		echo "ERRROR: could not mkimage install script"
-		exit 1
-	fi
-}
-
-pad_image() {
-	file="$1"
-	pad_size="$2"
-
-	if [ ! -f $file ]; then
-		echo "Creating empty $file"
-		touch $file
-	fi
-
-	size=$(du -b "$file" | cut -f 1)
-	if [ $size -gt $pad_size ]; then
-		echo "ERROR: $file too big"
-		exit 2
-	fi
-
-	if [ $size -lt $pad_size ]; then
-		echo "Padding $file from $size to $pad_size"
-		if ! truncate -s $pad_size $file; then
-			echo "ERROR: truncate failed for $file"
-			exit 3
-		fi
-	fi
-}
-
-generate_install_script
-pad_image u-boot.bin $SZ_512K		# at 0x80008000
-pad_image MLO $SZ_512K			# at 0x80088000
-pad_image u-boot.img $SZ_512K		# at 0x80108000
-pad_image boot.scr $SZ_512K		# at 0x80188000
-pad_image dtb $SZ_2M			# at 0x80208000
-pad_image zimage $SZ_8M			# at 0x80408000
-pad_image initramfs $SZ_20M		# at 0x80c08000
-
-if ! cat u-boot.bin MLO u-boot.img boot.scr dtb zimage initramfs > install-image; then
-	echo "ERROR: failed to create install image"
-	exit 3
+if [ $# -lt 1 ]; then
+  echo "usage: $0 [make | run [32 | 64]]"
+  exit 0
 fi
 
-if ! sudo src/omap34usbboot/out/usbboot src/omap34usbboot/out/omap3_aboot install-image; then
-	echo "ERROR: failed to flash install-image"
-	exit 4
-fi
+case "$1" in
+
+run)
+  case "$2" in 32|64) ;; *) echo "ERROR: specify 32 or 64"; exit 0 ;; esac
+
+  if ! sudo src/omap34usbboot/out/usbboot$2 src/omap34usbboot/out/omap3_aboot install-image; then
+	  echo "ERROR: failed to flash install-image"
+	  exit 4
+  fi
+;;
+
+make)
+  pad_image() {
+	  file="$1"
+	  pad_size="$2"
+
+	  if [ ! -f $file ]; then
+		  echo "Creating empty $file"
+		  touch $file
+	  fi
+
+	  size=$(du -b "$file" | cut -f 1)
+	  if [ $size -gt $pad_size ]; then
+		  echo "ERROR: $file too big"
+		  exit 2
+	  fi
+
+	  if [ $size -lt $pad_size ]; then
+		  echo "Padding $file from $size to $pad_size"
+		  if ! truncate -s $pad_size $file; then
+			  echo "ERROR: truncate failed for $file"
+			  exit 3
+		  fi
+	  fi
+  }
+
+  if ! mkimage -A arm -T script -C none -n "Install script" -d boot.script boot.scr; then
+	  echo "ERRROR: could not mkimage install script"
+	  exit 1
+  fi
+
+  pad_image u-boot.bin $SZ_512K		# at 0x80008000
+  pad_image MLO $SZ_512K			# at 0x80088000
+  pad_image u-boot.img $SZ_512K		# at 0x80108000
+  pad_image boot.scr $SZ_512K		# at 0x80188000
+  pad_image dtb $SZ_2M			# at 0x80208000
+  pad_image zimage $SZ_8M			# at 0x80408000
+  pad_image initramfs $SZ_20M		# at 0x80c08000
+
+  if ! cat u-boot.bin MLO u-boot.img boot.scr dtb zimage initramfs > install-image; then
+	  echo "ERROR: failed to create install image"
+	  exit 3
+  fi
+;;
+
+*)
+  echo "ERROR: $1 is not a command"
+;;
+
+esac
+
