anvl: Add support for partitioning, formatting and untarring the rootfs
Only do it if rootfs.tar.gz file is specified.

Signed-off-by: Tony Lindgren <tony@atomide.com>

diff --git a/omap-usb-install b/omap-usb-install
--- a/omap-usb-install
+++ b/omap-usb-install
@@ -28,6 +28,7 @@ SZ_20M=20971520
 update=0
 install=0
 dieid=""
+rootfs_file=""
 
 print_options() {
   echo "usage: $0 [-u | --update] [-irootfs.tar.gz | --install=rootfs.tar.gz]"
@@ -181,6 +182,85 @@ wait_for_emmc() {
   return 0
 }
 
+install_on_emmc() {
+  dieid=$1
+  emmc=$2
+  rootfs=$3
+
+  echo "Partitioning $emmc..."
+  if ! sudo /sbin/parted --script $emmc mklabel msdos; then
+    echo "ERROR: Could not mklabel"
+    exit 1
+  fi
+  if ! sudo /sbin/parted --script $emmc mkpart primary fat32 2048s 128MB; then
+    echo "ERROR: Could not add fat32 partition"
+    exit 2
+  fi
+  if ! sudo /sbin/parted --script $emmc mkpart primary ext4 128MB 100%; then
+    echo "ERROR: Could not add ext4 partition"
+    exit 3
+  fi
+
+  echo "Formatting new partitions on $emmc..."
+  if ! sudo mkfs.vfat $emmc-part1; then
+    echo "ERROR: Could not mkfs.vfat"
+    exit 4
+  fi
+  if ! sudo mkfs.ext4 $emmc-part2; then
+    echo "ERROR: Could not mkfs.ext4"
+    exit 5
+  fi
+
+  echo "Adding tmp directories for mounting vfat and ext4..."
+  if ! vfat=$(mktemp -d /tmp/XXXXXXXX-$dieid-vfat); then
+    echo "ERROR: Could not mktemp for vfat"
+    exit 6
+  fi
+  if ! ext4=$(mktemp -d /tmp/XXXXXXXX-$dieid-ext4); then
+    echo "ERROR: Could not mktemp for ext4"
+    exit 7
+  fi
+  if ! sudo mount $emmc-part1 $vfat; then
+    echo "ERROR: Could not mount vfat"
+    exit 8
+  fi
+  echo "Mounted vfat to temporary location $vfat"
+  if ! sudo mount $emmc-part2 $ext4; then
+    echo "ERROR: Could not mount ext4"
+    exit 9
+  fi
+  echo "Mounted ext4 to temporary location $ext4"
+
+  #
+  # REVISIT: Add copying of MLO and u-boot to $vfat here
+  #
+
+  echo "Untarring root file system to $ext4..."
+  if ! sudo tar zxf $rootfs -C $ext4; then
+    echo "ERROR: Untarring failed for $rootfs"
+    exit 11
+  fi
+
+  echo "Syncing, unmounting and cleaning up tmp directories..."
+  sync
+  if ! sudo umount $ext4; then
+    echo "ERROR: Could not umount ext4"
+    exit 12
+  fi
+  if ! sudo umount $vfat; then
+    echo "ERROR: Could not umount vfat"
+    exit 13
+  fi
+  if ! rmdir $ext4; then
+    echo "ERROR: Could not remove tmp dir for ext4"
+    exit 14
+  fi
+  if ! rmdir $vfat; then
+    echo "ERROR: Could not remove tmp dir for vfat"
+    exit 15
+  fi
+}
+
 #
 # Main program
 #
@@ -217,4 +297,20 @@ if [ "$install" == "1" ] && [ "$dieid" != "" ]; then
   if ! wait_for_emmc $disk; then
     exit 5
   fi
+
+  if [ "$rootfs_file" == "" ]; then
+    echo "WARNING: No rootfs specified, assuming manual install"
+    exit 6
+  fi
+
+  if [ ! -f $rootfs_file ]; then
+    echo "ERROR: Could not find file (or absolute path) for rootfs $rootfs_file"
+    exit 7
+  fi
+
+  if ! install_on_emmc $dieid $disk $rootfs_file; then
+    exit 8
+  fi
+  echo "Done, please power cycle the installed device"
+  exit 0
 fi
