anvl: Add support for just erasing the NAND
In some cases we just want to erase NAND.

diff --git a/omap-usb-install b/omap-usb-install
--- a/omap-usb-install
+++ b/omap-usb-install
@@ -26,6 +26,7 @@ SZ_8M=8388608
 SZ_20M=20971520
 
 update=0
+wipe=0
 loop=0
 tests=0
 install=0
@@ -43,9 +44,18 @@ main() {
     fi
   fi
 
+  if [ "$wipe" == "1" ]; then
+    echo "Wiping u-boot in NAND..."
+    if ! cold_flash images/erase-image; then
+      echo "ERROR: Could not wipe u-boot in NAND"
+      return 2
+    fi
+    return 0
+  fi
+
   if [ "$install" == "1" ]; then
     echo "Cold flashing over USB..."
-    if ! cold_flash; then
+    if ! cold_flash images/install-image; then
       echo "ERROR: Could not cold flash"
       return 2
     fi
@@ -114,7 +124,7 @@ check_options() {
     exit 0
   fi
 
-  if ! options=$(getopt -o ui::lt -l update,install::,loop,tests -- "$@"); then
+  if ! options=$(getopt -o uwi::lt -l update,wipe,install::,loop,tests -- "$@"); then
     print_options
     exit 1
   fi
@@ -125,6 +135,9 @@ check_options() {
     case $1 in
     -u|--update)
       update=1
+    ;;
+    -w|--wipe)
+      wipe=1
     ;;
     -i|--install)
       rootfs_file=$2
@@ -155,6 +168,8 @@ check_options() {
 }
 
 cold_flash() {
+  image=$1
+
   # Check for a locally compiled omap34usbboot binary first
   if [ -f src/omap34usbboot/out/usbboot ]; then
     prefix=src/omap34usbboot/out
@@ -186,7 +201,7 @@ cold_flash() {
       exit 4
     fi 
     dieid=$(echo $output | awk '{ split($0,a,"dieid: "); print substr(a[2], 1, 32) }')
-  done < <(sudo $prefix/usbboot $prefix/omap3_aboot images/install-image 2>&1)
+  done < <(sudo $prefix/usbboot $prefix/omap3_aboot $image 2>&1)
 
   if [ "$dieid" = "" ]; then
     echo "ERROR: failed to get dieid"
@@ -224,13 +239,22 @@ update_images() {
 
   if ! mkimage -A arm -T script -C none -n "Install script" -d src/scripts/boot.script images/boot.scr; then
     echo "ERRROR: could not mkimage install script"
-    exit 3
+    exit return 1
+  fi
+
+  if ! mkimage -A arm -T script -C none -n "Erase script" -d src/scripts/erase.script images/erase.scr; then
+    echo "ERRROR: could not mkimage erase script"
+    exit return 2
   fi
 
   pad_image images/u-boot.bin $SZ_512K    # at 0x80008000
   pad_image images/MLO $SZ_512K           # at 0x80088000
   pad_image images/u-boot.img $SZ_512K    # at 0x80108000
+
+  # One of these depending of the command line options
   pad_image images/boot.scr $SZ_512K      # at 0x80188000
+  pad_image images/erase.scr $SZ_512K	  # at 0x80188000
+
   pad_image images/dtb $SZ_2M             # at 0x80208000
   pad_image images/zimage $SZ_8M          # at 0x80408000
   pad_image images/initramfs $SZ_20M      # at 0x80c08000
@@ -238,7 +262,13 @@ update_images() {
   if ! cat images/u-boot.bin images/MLO images/u-boot.img images/boot.scr \
       images/dtb images/zimage images/initramfs > images/install-image; then
     echo "ERROR: failed to create install image"
-    exit 4
+    return 3
+  fi
+
+  if ! cat images/u-boot.bin images/MLO images/u-boot.img images/erase.scr > \
+      images/erase-image; then
+    echo "ERROR: failed to create erase image"
+    return 4
   fi
 
   return 0
